### PR TITLE
[YUNIKORN-2990] Add support for securityContext in the helm charts

### PR DESCRIPTION
**Pull request by pbacsko**
### What is this PR for?
Add support for various `securityContext` settings in the template.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2990

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by wilfred-s — CHANGES_REQUESTED** [review]
We should also add the same change to the admission controller deployment.

**Review by wilfred-s — APPROVED** [review]
LGTM +1
leaving open for others to comment on the changes

**Comment by josqu4red** [comment]
Could defaults be set to match the [container images](https://github.com/apache/yunikorn-k8shim/blob/master/docker/scheduler/Dockerfile#L19) ?

**Comment by craigcondit** [comment]
The values are meant for overrides. If blank they will already default to the container settings.

**Comment by josqu4red** [comment]
Right. I planned to submit [this change](https://github.com/apache/yunikorn-release/commit/191b35e6d57cb66d49bb55de666a478898e26e68) for policy reasons (but stopped at the Jira step)

**Comment by craigcondit** [comment]
I personally would rather not encode this (or any other specific values) into the default helm chart. Security context is something each environment policy differs on. It's not possible to construct one that will satisfy every policy. The default values are already secure; this PR simply allows setting them explicitly if required in certain environments.

**Comment by josqu4red** [comment]
Aside from this it would have been nice to reuse the values hierarchy (e.g `.Values.admissionController.podSecurityContext` instead of `.Values.admissionPodSecurityContext` etc.) don't you think?

**Pull request closed without merging**
