### PR TITLE
[YUNIKORN-2541] Upgrade golang.org/x/net for CVEs

### PR DESCRIPTION
**Pull request by wilfred-s**
### What is this PR for?
Update golang dependencies for CVEs

### What type of PR is it?
* [X] - Improvement

### What is the Jira issue?
* https://issues.apache.org/jira/browse/YUNIKORN-2541
The jira was closed but skipped the release repo and dependabot complains about the CVE

### How should this be tested?
NA

### CODE REVIEW

**Review by chia7712 — APPROVED** [review]
LGTM

**Review by chenyulin0719 — CHANGES_REQUESTED** [review]
The indirect requires are changed after running 'go mod tidy'. 
- golang.org/x/sys -> v0.18.0
- golang.org/x/term -> v0.18.0

**Comment by wilfred-s** [comment]
commit updated, go mod tidy change was still sitting staged locally

**Review by chenyulin0719 — APPROVED** [review]
+1 LGTM

**Review by pbacsko — APPROVED** [review]
+1

**Pull request closed without merging**
